### ISSUE TITLE
Manca la parte in reverse.

### ISSUE THREAD

**Issue by Xiradorn** [bruninoit/toptentopics#11]
Mancano i moduli di eliminazione dei settaggi. Inoltre non sarebbe consigliabile spostare le configurazioni in una tabella a parte così quando elimini lo fai in un colpo solo? Senno nel config pure va bene

**Comment by bruninoit** [comment]
Ora guardo

**Comment by bruninoit** [comment]
Si effettivamente mancano. Meglio lasciarle nella tabella config, è fatta apposta e si cambiano con un semplice comando senza dover lanciare query ecc

**Comment by bruninoit** [comment]
Sai che, non serve metterli per i config. Ecco perché non li avevo messi: l'operazione contraria viene dedotta, o almeno, cosi dovrebbe essere.

**Comment by bruninoit** [comment]
(Lo stesso anche per i moduli)

**Comment by Xiradorn** [comment]
Fatta io nell'ultima release di cui hai fatto già il merging.
